version: "3.3"  # optional since v1.27.0
services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'bluebank'
    ports:
      - "3306:3306"